# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: echo.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'echo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\necho.proto\x12\x04\x65\x63ho\x1a\x1egoogle/protobuf/duration.proto\"\x07\n\x05\x45mpty\"\x1e\n\x0b\x45\x63hoRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"6\n\x0c\x45\x63hoResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x15\n\rmessage_count\x18\x02 \x01(\x05\"y\n\x1aServerStreamingEchoRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x15\n\rmessage_count\x18\x02 \x01(\x05\x12\x33\n\x10message_interval\x18\x03 \x01(\x0b\x32\x19.google.protobuf.Duration\".\n\x1bServerStreamingEchoResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"-\n\x1a\x43lientStreamingEchoRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"4\n\x1b\x43lientStreamingEchoResponse\x12\x15\n\rmessage_count\x18\x01 \x01(\x05\x32\xaf\x04\n\x0b\x45\x63hoService\x12-\n\x04\x45\x63ho\x12\x11.echo.EchoRequest\x1a\x12.echo.EchoResponse\x12\x34\n\tEchoAbort\x12\x11.echo.EchoRequest\x1a\x12.echo.EchoResponse\"\x00\x12 \n\x04NoOp\x12\x0b.echo.Empty\x1a\x0b.echo.Empty\x12\\\n\x13ServerStreamingEcho\x12 .echo.ServerStreamingEchoRequest\x1a!.echo.ServerStreamingEchoResponse0\x01\x12\x63\n\x18ServerStreamingEchoAbort\x12 .echo.ServerStreamingEchoRequest\x1a!.echo.ServerStreamingEchoResponse\"\x00\x30\x01\x12\\\n\x13\x43lientStreamingEcho\x12 .echo.ClientStreamingEchoRequest\x1a!.echo.ClientStreamingEchoResponse(\x01\x12;\n\x0e\x46ullDuplexEcho\x12\x11.echo.EchoRequest\x1a\x12.echo.EchoResponse(\x01\x30\x01\x12;\n\x0eHalfDuplexEcho\x12\x11.echo.EchoRequest\x1a\x12.echo.EchoResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'echo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=52
  _globals['_EMPTY']._serialized_end=59
  _globals['_ECHOREQUEST']._serialized_start=61
  _globals['_ECHOREQUEST']._serialized_end=91
  _globals['_ECHORESPONSE']._serialized_start=93
  _globals['_ECHORESPONSE']._serialized_end=147
  _globals['_SERVERSTREAMINGECHOREQUEST']._serialized_start=149
  _globals['_SERVERSTREAMINGECHOREQUEST']._serialized_end=270
  _globals['_SERVERSTREAMINGECHORESPONSE']._serialized_start=272
  _globals['_SERVERSTREAMINGECHORESPONSE']._serialized_end=318
  _globals['_CLIENTSTREAMINGECHOREQUEST']._serialized_start=320
  _globals['_CLIENTSTREAMINGECHOREQUEST']._serialized_end=365
  _globals['_CLIENTSTREAMINGECHORESPONSE']._serialized_start=367
  _globals['_CLIENTSTREAMINGECHORESPONSE']._serialized_end=419
  _globals['_ECHOSERVICE']._serialized_start=422
  _globals['_ECHOSERVICE']._serialized_end=981
# @@protoc_insertion_point(module_scope)
