# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import echo_pb2 as echo__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in echo_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EchoServiceStub(object):
    """A simple echo service.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Echo = channel.unary_unary(
                '/echo.EchoService/Echo',
                request_serializer=echo__pb2.EchoRequest.SerializeToString,
                response_deserializer=echo__pb2.EchoResponse.FromString,
                _registered_method=True)
        self.EchoAbort = channel.unary_unary(
                '/echo.EchoService/EchoAbort',
                request_serializer=echo__pb2.EchoRequest.SerializeToString,
                response_deserializer=echo__pb2.EchoResponse.FromString,
                _registered_method=True)
        self.NoOp = channel.unary_unary(
                '/echo.EchoService/NoOp',
                request_serializer=echo__pb2.Empty.SerializeToString,
                response_deserializer=echo__pb2.Empty.FromString,
                _registered_method=True)
        self.ServerStreamingEcho = channel.unary_stream(
                '/echo.EchoService/ServerStreamingEcho',
                request_serializer=echo__pb2.ServerStreamingEchoRequest.SerializeToString,
                response_deserializer=echo__pb2.ServerStreamingEchoResponse.FromString,
                _registered_method=True)
        self.ServerStreamingEchoAbort = channel.unary_stream(
                '/echo.EchoService/ServerStreamingEchoAbort',
                request_serializer=echo__pb2.ServerStreamingEchoRequest.SerializeToString,
                response_deserializer=echo__pb2.ServerStreamingEchoResponse.FromString,
                _registered_method=True)
        self.ClientStreamingEcho = channel.stream_unary(
                '/echo.EchoService/ClientStreamingEcho',
                request_serializer=echo__pb2.ClientStreamingEchoRequest.SerializeToString,
                response_deserializer=echo__pb2.ClientStreamingEchoResponse.FromString,
                _registered_method=True)
        self.FullDuplexEcho = channel.stream_stream(
                '/echo.EchoService/FullDuplexEcho',
                request_serializer=echo__pb2.EchoRequest.SerializeToString,
                response_deserializer=echo__pb2.EchoResponse.FromString,
                _registered_method=True)
        self.HalfDuplexEcho = channel.stream_stream(
                '/echo.EchoService/HalfDuplexEcho',
                request_serializer=echo__pb2.EchoRequest.SerializeToString,
                response_deserializer=echo__pb2.EchoResponse.FromString,
                _registered_method=True)


class EchoServiceServicer(object):
    """A simple echo service.
    """

    def Echo(self, request, context):
        """One request followed by one response
        The server returns the client message as-is.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EchoAbort(self, request, context):
        """Sends back abort status.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NoOp(self, request, context):
        """One empty request, ZERO processing, followed by one empty response
        (minimum effort to do message serialization).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ServerStreamingEcho(self, request, context):
        """One request followed by a sequence of responses (streamed download).
        The server will return the same client message repeatedly.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ServerStreamingEchoAbort(self, request, context):
        """One request followed by a sequence of responses (streamed download).
        The server abort directly.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClientStreamingEcho(self, request_iterator, context):
        """A sequence of requests followed by one response (streamed upload).
        The server returns the total number of messages as the result.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FullDuplexEcho(self, request_iterator, context):
        """A sequence of requests with each message echoed by the server immediately.
        The server returns the same client messages in order.
        E.g. this is how the speech API works.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HalfDuplexEcho(self, request_iterator, context):
        """A sequence of requests followed by a sequence of responses.
        The server buffers all the client messages and then returns the same
        client messages one by one after the client half-closes the stream.
        This is how an image recognition API may work.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EchoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Echo': grpc.unary_unary_rpc_method_handler(
                    servicer.Echo,
                    request_deserializer=echo__pb2.EchoRequest.FromString,
                    response_serializer=echo__pb2.EchoResponse.SerializeToString,
            ),
            'EchoAbort': grpc.unary_unary_rpc_method_handler(
                    servicer.EchoAbort,
                    request_deserializer=echo__pb2.EchoRequest.FromString,
                    response_serializer=echo__pb2.EchoResponse.SerializeToString,
            ),
            'NoOp': grpc.unary_unary_rpc_method_handler(
                    servicer.NoOp,
                    request_deserializer=echo__pb2.Empty.FromString,
                    response_serializer=echo__pb2.Empty.SerializeToString,
            ),
            'ServerStreamingEcho': grpc.unary_stream_rpc_method_handler(
                    servicer.ServerStreamingEcho,
                    request_deserializer=echo__pb2.ServerStreamingEchoRequest.FromString,
                    response_serializer=echo__pb2.ServerStreamingEchoResponse.SerializeToString,
            ),
            'ServerStreamingEchoAbort': grpc.unary_stream_rpc_method_handler(
                    servicer.ServerStreamingEchoAbort,
                    request_deserializer=echo__pb2.ServerStreamingEchoRequest.FromString,
                    response_serializer=echo__pb2.ServerStreamingEchoResponse.SerializeToString,
            ),
            'ClientStreamingEcho': grpc.stream_unary_rpc_method_handler(
                    servicer.ClientStreamingEcho,
                    request_deserializer=echo__pb2.ClientStreamingEchoRequest.FromString,
                    response_serializer=echo__pb2.ClientStreamingEchoResponse.SerializeToString,
            ),
            'FullDuplexEcho': grpc.stream_stream_rpc_method_handler(
                    servicer.FullDuplexEcho,
                    request_deserializer=echo__pb2.EchoRequest.FromString,
                    response_serializer=echo__pb2.EchoResponse.SerializeToString,
            ),
            'HalfDuplexEcho': grpc.stream_stream_rpc_method_handler(
                    servicer.HalfDuplexEcho,
                    request_deserializer=echo__pb2.EchoRequest.FromString,
                    response_serializer=echo__pb2.EchoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'echo.EchoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('echo.EchoService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EchoService(object):
    """A simple echo service.
    """

    @staticmethod
    def Echo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/echo.EchoService/Echo',
            echo__pb2.EchoRequest.SerializeToString,
            echo__pb2.EchoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EchoAbort(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/echo.EchoService/EchoAbort',
            echo__pb2.EchoRequest.SerializeToString,
            echo__pb2.EchoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NoOp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/echo.EchoService/NoOp',
            echo__pb2.Empty.SerializeToString,
            echo__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ServerStreamingEcho(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/echo.EchoService/ServerStreamingEcho',
            echo__pb2.ServerStreamingEchoRequest.SerializeToString,
            echo__pb2.ServerStreamingEchoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ServerStreamingEchoAbort(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/echo.EchoService/ServerStreamingEchoAbort',
            echo__pb2.ServerStreamingEchoRequest.SerializeToString,
            echo__pb2.ServerStreamingEchoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClientStreamingEcho(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/echo.EchoService/ClientStreamingEcho',
            echo__pb2.ClientStreamingEchoRequest.SerializeToString,
            echo__pb2.ClientStreamingEchoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FullDuplexEcho(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/echo.EchoService/FullDuplexEcho',
            echo__pb2.EchoRequest.SerializeToString,
            echo__pb2.EchoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HalfDuplexEcho(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/echo.EchoService/HalfDuplexEcho',
            echo__pb2.EchoRequest.SerializeToString,
            echo__pb2.EchoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
